version: '2'
services:
    advproject_apache:
      container_name: advproject_apache
      build: apache
      restart: always
      volumes:
        - ../public_html:/var/www
        - ./apache/sites-available:/etc/apache2/sites-available
      ports:
        - 80:80
      environment:
        - VIRTUALHOST=advproject.dev

    advproject_mongodb:
      image: mongo:latest
      container_name: "advproject_mongodb"
      restart: always
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - advproject_db:/data/db
      ports:
        - 27017:27017
      command: mongod --smallfiles # --quiet

    advproject_scala:
      container_name: advproject_scala
      working_dir: /app
      command: sbt ~reStart
      build: scala
      restart: always
      volumes:
        - ../:/app
      ports:
        - 8080:8080
      links:
        - advproject_mongodb:mongo

volumes:
    advproject_db:
